### ISSUE TITLE
Wrong page played on clock restart

### ISSUE THREAD

**Issue by fjl** [hotchk155/matrix-seq-firmware2#1]
Firmware version 1.00

Repro steps

- Create empty project
- Input gates on page 1A
- Input different gates on page 1B
- Page 1B is selected
- Ensure background play is disabled (press LOOP+PAGE twice, it shows "OFF")
- Press play on external clock
- Gates from page 1A are playing

It should play page 1B instead because background play is disabled.

**Comment by fjl** [comment]
Turns out this is not related to MIDI clock at all, and it's not really
about triggering background play either. The bug is that it plays the
wrong page on clock restart.

Simplified repro steps:

- Empty project
- Input gates on page 1A
- Input different gates on page 1B
- Page 1B is selected
- Press CV+RUN
- Gates from page 1A are playing

Notably, the page indicator in the bottom right does not show up,
so it's definitely not in background play mode.

**Comment by fjl** [comment]
This happens because resetting the clock triggers a reset of the layer:

https://github.com/hotchk155/matrix-seq-firmware2/blob/68ce408af545acb7fb4d2c0e322921c370cc4902/NoodleBox/source/sequence_layer.h#L326-L330

which sets the play page to zero:

https://github.com/hotchk155/matrix-seq-firmware2/blob/68ce408af545acb7fb4d2c0e322921c370cc4902/NoodleBox/source/sequence_layer.h#L317

**Comment by fjl** [comment]
I can confirm that 5ae53eb fixes the issue for me.

**Comment by hotchk155** [comment]
fixed in release 1.1
