### ISSUE TITLE
Weird behaviour when AUX input used to receive a clock reset

### ISSUE THREAD

**Issue by hotchk155** [hotchk155/matrix-seq-firmware2#17]
I want to sync Noodlebox to my Beatstep Pro (BSP as master). I connected them by using the clock out of my BSP to the Noodlebox sync in. This works perfectly, they stay in sync tightly. I also want to reset the Noodlebox using the Aux in. I used a trigger on one of my BSP channels every 16 steps and connected it to the Aux in. I have set the aux behavior in the menu to Reset.  Now it acts weirdly and each time differently: speeding up the clock, stopping it, resetting every second step, and so on.

[Laurens Alberts]

**Comment by RomainWELKER** [comment]
I encounter the same behaviour with other clock sources from Eurorack modules, and when it's stuck, the only way to make it run normally is to turn the Noodlebox off, then to turn it back on.

**Comment by RomainWELKER** [comment]
By the way, the Noodlebox freezes with external reset even when clocked by its internal clock.

**Comment by hotchk155** [comment]
fixed in release 1.1
