### ISSUE TITLE
Layer mute keys are confusing

### ISSUE THREAD

**Issue by fjl** [hotchk155/matrix-seq-firmware2#2]
Firmware version: 1.00

The shortcut to mute a specific layer is a bit confusing because you need
to press LAYER+PAGE, then release PAGE, and then press the layer key.
When I first tried the mutes, I just held LAYER+PAGE and then pressed
the layer key, but it doesn't work. My first reaction was thinking mutes
are not implemented yet 😄. Only after reading the manual did I realize
that PAGE needs to be released for it to work.

Couldn't LAYER+PAGE+\[1234\] be made to work as well?

**Comment by hotchk155** [comment]
it could but it would need a change in some of the core ui code, since it currently works with key combinations of max 2 keys... i'll keep this one in mind though

**Comment by fjl** [comment]
It's actually no problem, I got used to the correct way immediately after discovering it, just wanted to share my initial impression.

**Comment by hotchk155** [comment]
fixed in release 1.1
