### ISSUE TITLE
Feature Request: Visual indicator of octaves in view

### ISSUE THREAD

**Issue by crstffr** [hotchk155/matrix-seq-firmware2#23]
One thing that continues to confuse me while I'm working with the NoodleBox is that I have no way of knowing where I am looking on the "piano roll". Without inserting a pitch, I have no way of knowing if I am looking at the bottom, middle, or top of the pitch range. To solve this I end up vertically scrolling up and down quite a bit trying to get a sense of where I am.

You are already doing a great many things with the limited UI capabilities of the custom screen you've built, so I know there likely isn't much room for extra information. But I would find it useful if there was some indicator as to which octaves are currently in view.

**Comment by hotchk155** [comment]
good points - gonna have a think how best to do this.... Cheers/Jason

**Comment by hotchk155** [comment]
fixed in release 1.1
