### ISSUE TITLE
cut a release?

### ISSUE THREAD

**Issue by ScrumpyJack** [hotchk155/matrix-seq-firmware2#29]
Hey can we get a release, and possibly some upgrade instructions? that would be awesome.

**Comment by hotchk155** [comment]
Hey sorry just spotted this! Release 1.1 beta came out in August and I announced it on the mailing list at the time. I've now added a releases page to the web site https://six4pix.net/product/noodlebox/#tab-firmware-updates
Cheers
Jason

**Comment by hotchk155** [comment]
BTW firmware update instructions are in the manual https://github.com/hotchk155/Noodlebox/raw/master/docs/Noodlebox%20User%20Guide.pdf
currently they are on p32
Cheers
Jason
