### ISSUE TITLE
Feature request: Mute multiple tracks

### ISSUE THREAD

**Issue by ScrumpyJack** [hotchk155/matrix-seq-firmware2#3]
Currently you can't mute multiple tracks by pressing Layer+Page, then 1 and 2 for example. You can only press 1, then 2. Would be neat to be able to mute tracks simultaneously.

**Comment by hotchk155** [comment]
yeah i had a couple of requests around the way mutes work - the UI code currently recognises combinations of 2 keys only but that could be changed so that LAYER+PAGE+1+2 (for example) could all be held at same time..

**Comment by hotchk155** [comment]
fixed in release 1.1
