### ISSUE TITLE
Feature request: Scroll vertically when transposing

### ISSUE THREAD

**Issue by ScrumpyJack** [hotchk155/matrix-seq-firmware2#4]
If i want to shift a sequence up or down, i hold CV+Rand, and move the sequence with the encoder, but the page doesn't scroll with the notes, so moving the sequence a couple of octaves up, i can't see what i'm doing. Have i missed something?

**Comment by hotchk155** [comment]
nope you are correct, this would be a nice add.. on the list!

**Comment by hotchk155** [comment]
fixed in release 1.1
