### ISSUE TITLE
Wrong loop length when visiting page for the first time

### ISSUE THREAD

**Issue by fjl** [hotchk155/matrix-seq-firmware2#5]
Firmware version: 1.00

Repro:

- Empty project
- Loop per layer is enabled
- Background play is disabled
- Page 1A is selected
- Set loop to first eight steps
- Switch to page 1B
- Loop ruler shows on first eight steps
- But: first 16 steps are played, beyond loop ruler

I think this is wrong, it should play the first eight steps instead.

In loop per page mode, the ruler displays on the first 16 steps when switching to page 1B
for the first time, and it plays 16 steps as well. This is acceptable because it basically gets
the default 16 steps.

Note that the loop length also works correctly in loop per layer mode if I first go to page 1B,
then back to 1A, then set the loop length to eight. It's important not to visit page 1B before
setting the loop length for this bug to happen.

**Comment by fjl** [comment]
This happens because pages are cleared when they are first created.

https://github.com/hotchk155/matrix-seq-firmware2/blob/175a399a34bb08be76b96420baf22a4be29032ac/NoodleBox/source/sequence_editor.h#L1190

https://github.com/hotchk155/matrix-seq-firmware2/blob/175a399a34bb08be76b96420baf22a4be29032ac/NoodleBox/source/sequence_layer.h#L649

https://github.com/hotchk155/matrix-seq-firmware2/blob/175a399a34bb08be76b96420baf22a4be29032ac/NoodleBox/source/sequence_page.h#L219

Not sure what the best solution would be. Maybe it would be simpler to just pre-create all pages instead of
initializing them on demand? Alternatively, `prepare_page` could set the loop points of the new page to the
loop points of the previous page.

**Comment by hotchk155** [comment]
Thanks for the great analysis on this. I did change the way that the "loop points defined per page" setting worked quite late on in the development and I guess this bug crept in then.

**Comment by fjl** [comment]
This is fixed for me with the above commit.

**Comment by hotchk155** [comment]
> This is fixed for me with the above commit.

Cool! I am gonna do a roll-up bug fix release when i have a few more fixes done (to save too many versions). I am curious how you're able to test - did you use the sysex utility and bootloader, or have you got it connected up to a JTAG programmer? Cheers/Jason

**Comment by fjl** [comment]
I'm using the sysex for upgrades, don't have a JTAG programmer :).

**Comment by hotchk155** [comment]
fixed in release 1.1
