### ISSUE TITLE
Randomly generated notes exceeding grid bounds?

### ISSUE THREAD

**Issue by hotchk155** [hotchk155/matrix-seq-firmware2#8]
At one point RAND + LOOP was generating notes right at the bottom of the grid (so low, possiblly MIDI note 0, pitch but random gates). However, I've not been able to reproduce that this morning.

[Ian Heath]

**Comment by drGrov** [comment]
I think this might be down to my misunderstanding of how RAND+LOOP works. It seems that if you've got higher notes displayed (e.g. a page with a single C5 note) and then use RAND+LOOP it  generates data around C2 and so all you see are the gates changing.

**Comment by hotchk155** [comment]
I've played around with this and I think your explanation is right, let me know if you see it again! Closing for now
Cheers/Jason
